apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ntfy
resources:
  - configmap.yaml
  - deployment.yaml
  - httproute.yaml
  - persistentvolumeclaim.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
configMapGenerator:
  - name: templates
    files:
      - templates/flux.yml
images:
  - name: docker.io/binwiederhier/ntfy
    newTag: v2.28.0 # {"$imagepolicy": "flux-system:ntfy:tag"}
    digest: sha256:6ef4b819f722fccdc036af611c4774cfdc2de821ab74fdd48bbf4c9d6f8973da # {"$imagepolicy": "flux-system:ntfy:digest"}
labels:
  - pairs:
      app.kubernetes.io/part-of: ntfy
      app.kubernetes.io/version: v2.28.0 # {"$imagepolicy": "flux-system:ntfy:tag"}
