apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ntfy
resources:
  - configmap.yaml
  - deployment.yaml
  - httproute.yaml
  - persistentvolumeclaim.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
configMapGenerator:
  - name: templates
    files:
      - templates/flux.yml
images:
  - name: docker.io/binwiederhier/ntfy
    newTag: v2.29.0 # {"$imagepolicy": "flux-system:ntfy:tag"}
    digest: sha256:4c599cf0818965782f93f652bd843e92714992e84d6b88ad17713dc0951cda1f # {"$imagepolicy": "flux-system:ntfy:digest"}
labels:
  - pairs:
      app.kubernetes.io/part-of: ntfy
      app.kubernetes.io/version: v2.29.0 # {"$imagepolicy": "flux-system:ntfy:tag"}
