apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - configmap.yaml
  - deployment.yaml
  - httproute.yaml
  - persistentvolumeclaim.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
secretGenerator:
  - name: immich-config
    files:
      - immich-config.json
images:
  - name: ghcr.io/immich-app/immich-server
    newTag: v3.2.4 # {"$imagepolicy": "flux-system:immich-server:tag"}
    digest: sha256:d317916b28090c33eb36b308464ea391f8b7df1d850fcfea227a39ec879718c2 # {"$imagepolicy": "flux-system:immich-server:digest"}
labels:
  - pairs:
      app.kubernetes.io/part-of: immich
      app.kubernetes.io/version: v3.2.4 # {"$imagepolicy": "flux-system:immich-server:tag"}
