apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgresql
resources:
  - cluster.yaml
images:
  - name: ghcr.io/cloudnative-pg/postgresql
    newTag: 18.6-standard-trixie # {"$imagepolicy": "flux-system:postgresql:tag"}
    digest: sha256:670026a375a908c3c2f6b5eeb1c56a06d2a15d375959f401d2aed8b8dd99f50e # {"$imagepolicy": "flux-system:postgresql:digest"}
  - name: ghcr.io/tensorchord/vchord-scratch
    newTag: pg18-v1.1.1 # {"$imagepolicy": "flux-system:vchord-scratch:tag"}
    digest: sha256:bdea43bed2a414e21bbf71767bf6f0739747ac480b267b51772dc214ac28dcb3 # {"$imagepolicy": "flux-system:vchord-scratch:digest"}
labels:
  - pairs:
      app.kubernetes.io/version: 18.6-standard-trixie # {"$imagepolicy": "flux-system:postgresql:tag"}
configurations:
  - images.yaml
