apiVersion: v1
kind: Secret
metadata:
  name: ntfy-headers
  namespace: flux-system
stringData:
  headers: ENC[AES256_GCM,data:xg6707TUZetbrLgQcuRLIOcwIjzRJ88NhiNfmytYTByweEm853BOt2t1c387cO3EVm/T2a0SjtTf1ZhvvpGEhT2SOYhaFg==,iv:4ibmi7EO1Di4w73V2OHEyHIJlbY2e2yvFZp8vY9hD34=,tag:CMyLdQCcG4OShVwdCtW9nQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHJDOTd2MzdQ
        dGxWU0NZcHlwdEV3d25GblF6V05BbkhYNlhGdHU2VWsxYkFhR3hyYmZUVmc3dkNZ
        MUh3UkE1dkFYazBjS3BaTG84RnVOOUY0Q2tBeHNsNTNyb29TajJIcHdDYkx4WVlK
        Q3RhZ045clo3WkE1dUJpMm5rV2FGMW5PamtkblFlTjk5b04xdWFyUDg0QkR6SnFh
        SlRES1ZWZlIzdXJpcVdnZXNScEZVOE12L1JiUEZCb0ZxdlpEaFl2TkJPaEZXckxN
        OGJ3aDJmVWVzRktUMUdUc3l2TlRnTUFxemJiRnVUN3NzL251K3pPT0hVdlg4YnZl
        UmxNdUxqVS9ydHJSaVJEU0pYemwva0I0YVU4ZmFYdm5YRTBrOXNTTkNBQ3U1WGF3
        KytwVWljY0VsekpORDBkZE5BekVwUXFLVkJPRStWOVZWRDU2V3N3Syt5VlFEdEdn
        SVpsMWphVldKb2I3Q25IWWZ5Zlh3UUJxSDRoaTNqU0p0V3NlYUJQTUZBT255VkVa
        MzY4aVBFeGRTeGQ2NFcrTXZYaFQ3a05RQW5DVE12SjN1bDZ6MkpDRkMrV2k4OU5P
        bGswNEN6TzVudnd1NkRiZDRROUFkVzFkcW9FaXdzdGlnYmdvM05QNlpsZk9uL1Nl
        eFpNTlhVdDhZZi93TkF2K3NqTFcySGIrR25XWHdoNkliczYxWkZvK01GbWJVaUMr
        RkRLSmg1Q0F5Ri81VWtDWGhkVEdRaE5UZUhSY2JyS0hGaWlzazYzYUVReEdIZ2FT
        TmpUTktMKzFmZFZVUVpzWGZJbHpFZUhWanJHNWxJUWxxMGMvOC9qdjQ2bUFqSGZ6
        ZFUxaWdncEJOVFh5bC9oRkhyeDFmc0JXbXh5N21HWkNVaytBQXJXb3ZEM2k1YkJC
        cFJQMDlyNlNEdDJGZ0d3dUJiZFZrc2tubnZzckl3S2F5MXd0VGxTYTh4aWtBdVcy
        Ym81aFRZczJZbUtmc245eGMwSzdCN0ZDL3BXVCs4WVE0UkRYaU1teHM3WjlVUXFB
        TWRaUDdqcVF2bFVoazljRmR0ZEtma0RXcW5vNWFnMUFtVUh2dGZrM0RyWE9heHRC
        SFlwL1gzT0xqVWh5VWRRL2VMMVBtU01TTnVVd1J0d01YUzlYT2RkNkFmZlpNS2tO
        K0dYbFZNQXdJRkNkQWZacndCZDV1S01aSDVjYzBtV2p4dVpKMW8ySG5Cb0tZaEts
        ZXN1R0VBYkptSDRtbFcxRDVJUkR2Qlh3eEtEdTN2emlFdVhidmpEZVV3REFiRHJy
        ZFEwVjhsTS9BZnVUM292TDdVT0p3NllBU0VEUTlvWHd6WUdvQVg3Y3N1WitQMG9N
        OTBJeGVLNHZ5amlHRmplSi9aSU0vVFYwMm9qc1VpV0JKZ2pmWi8yMTg1d0NIS1Yx
        TTN0Z3d3Ui9wZFZxanFRUVpRS0dpUzZSdDc3d2sxaXhYcjhmWldIdVhjZmFwTnB6
        TUpRL3RsakpzTk9wYk81T01FTWVwczNIU2E4UFZEbGhKS2dUYkl3OWlyM01oRmVV
        cm9pSStkNUg0NEZYamZoeXYyKzZ4cExXTDRzWHN5WENOZVFrNDdWa0VvRVpoT3dL
        TlR3WFFjQ3dzenZvUEx0S3VQc0JYZ3QraU1kekc3Umh1cjIva1hPN2tkZEhJalBq
        c1NOa3pZaGUxbVBWcjJnUnJNUWlUSUh3VTVmTHdxSmkvU1pQYjB2eTh3TmNNbDVp
        a3ljSFR2emZGb3V1S3hXaWVEVmZqQzRmb3ViSUJqQnFqd3hwNG9MWDNQQWw5alU5
        bkRleGxKdDBYWTc5SW40aVJweHFibktUZFFWT211SGF0eXNzWjR6cU1kNEVqU0Nl
        UHh2bEFGVFhTOHZhYnZMbTI5UDRuMjJqWE1tR1hEck9yZmllcTNEcmJQNzRxclV3
        MGQ2Ky9kL1pSaklPRlhlY3k5RmpFbllValRJUXBNUzM4Z3NHUlVlZHJaMjdBdwp5
        QmllVk1BaUJmUlMxZ2dWdFJqUnJsajZoZjZkT2Y2RmdLaUtHbytOVVNNCi0tLSBM
        WkxMVFRuclJodGZ1MU9XTXhEYitESmxkclF1YWpiWExMbk0xa084cW5nCp999COr
        O1lA5FeiGVBlxbvWOpZOWstUIOrTrGwcQfaKThEh3KAihOelr5sPocppo/8iazG4
        fyhKO47I+HZInSg=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-18T00:55:23Z"
  mac: ENC[AES256_GCM,data:0WSeuBFZVNQdXR9eQ4GzLoH8df48rJtppHai3NpLt06DjuuGvMrQMmGXu1sEA5T+E0vQQ8m0HfNPxObamB5Mt7wZOkXVPr46yX2fM3cF0xVBOjzda/guLELIA0qw9GdVzp+yomTmu+iOlECrMjnJYb4z+HNaiwnDRKstW3Un/F0=,iv:HMcLMEho3vcCkZQbJZiYU54CdBxxkIn6YpRbheOq9gA=,tag:1IopI2VXtQ0/YwaSpmKvwA==,type:str]
  version: 3.13.3
