apiVersion: apps/v1
kind: Deployment
metadata:
  name: headlamp
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/instance: headlamp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: headlamp
      app.kubernetes.io/instance: headlamp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: headlamp
        app.kubernetes.io/instance: headlamp
    spec:
      serviceAccountName: headlamp
      automountServiceAccountToken: true
      enableServiceLinks: false
      hostUsers: true
      securityContext:
        runAsUser: 100
        runAsGroup: 101
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: headlamp-plugin-cert-manager
          image: ghcr.io/headlamp-k8s/headlamp-plugin-cert-manager
          command:
            - /bin/sh
            - -c
            - cp -r /plugins/* /headlamp/plugins/
          volumeMounts:
            - name: headlamp-plugins
              mountPath: /headlamp/plugins
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
        - name: headlamp-plugin-flux
          image: ghcr.io/headlamp-k8s/headlamp-plugin-flux
          command:
            - /bin/sh
            - -c
            - cp -r /plugins/* /headlamp/plugins/
          volumeMounts:
            - name: headlamp-plugins
              mountPath: /headlamp/plugins
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      containers:
        - name: headlamp
          image: ghcr.io/headlamp-k8s/headlamp
          envFrom:
            - configMapRef:
                name: headlamp
            - secretRef:
                name: oidc
          ports:
            - name: http
              containerPort: 4466
              protocol: TCP
          volumeMounts:
            - name: headlamp-plugins
              mountPath: /headlamp/plugins
              readOnly: true
            - name: headlamp-tmp
              mountPath: /tmp
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          startupProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: headlamp-plugins
          emptyDir: {}
        - name: headlamp-tmp
          emptyDir: {}
