apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: headlamp
resources:
  - clusterrolebinding.yaml
  - configmap.yaml
  - deployment.yaml
  - httproute.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
images:
  - name: ghcr.io/headlamp-k8s/headlamp
    newTag: v0.45.0
    digest: sha256:db3f0e0fc58d358d41daa3fe7fc852437552c7ee873c3645470f7b86a8e0db49
  - name: ghcr.io/headlamp-k8s/headlamp-plugin-flux
    newTag: v0.7.0
    digest: sha256:636c7a5ae0d4eb196c192f8f1cde06f20f1f5ebdf1863f6e57d22444d8b8360c
labels:
  - pairs:
      app.kubernetes.io/part-of: headlamp
      app.kubernetes.io/version: v0.45.0
