apiVersion: v1
kind: Secret
metadata:
  name: oidc
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/instance: headlamp
type: Opaque
stringData:
  HEADLAMP_CONFIG_OIDC_CLIENT_ID: ENC[AES256_GCM,data:V5xoH2v4H+A=,iv:d6rkM80XrxnxCatniOxVaGK0DOoDyxuzTcxuvfKwtHk=,tag:oe96Klcc1P5/dOaxcs+GhA==,type:str]
  HEADLAMP_CONFIG_OIDC_IDP_ISSUER_URL: ENC[AES256_GCM,data:0gqs+IkwZkh5s3Pu5JEP1N/ZPXPtdgvwv4sABB+RwPoq7sk=,iv:0l0ejfwNgj9eC2Qz3+zxufZn/ULgW3CRva3HrTWoTOw=,tag:oSzlyZvrxKkxgbU63o0dSg==,type:str]
  HEADLAMP_CONFIG_OIDC_SCOPES: ENC[AES256_GCM,data:UXfgb9uyojY+AfoWPqSA6FJ+d8Ngj4wMSBE7,iv:2w9r3keQEU31AQb/s7Gx73shK+mdsIwCs33hqR0OvHQ=,tag:jkaFOdmWzxiNVedq5CH/eA==,type:str]
  HEADLAMP_CONFIG_OIDC_USE_PKCE: ENC[AES256_GCM,data:hLd3Jw==,iv:b4B+lJfQXxaI4RCQC7JUoq6qZcLrxkUFgpRoa5q6YNE=,tag:f47EoxY/IqhANkVJ1QPcQQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGRVOTlJM2Zx
        YUVIY1ROTEJQdlhYMzhWWDg2NWFPcnBlK3pQN2ViT1ZRRGhMSjZabm5lNEJVTlhq
        dFhwYkZpbkdORkZVZit4UVJ4THdwNGlmU3NqNmRQVUtMSjlNMy9aeE5TMHJhZ2pj
        anlUbkFMNXMxekFTd21oNDJYQ25sNUZEeDY3N1NoNUpQK2hFRVdvOGl1bmNndjFm
        S3dZSTU4YU9tclhsRFdnNG55cUFtcGFiUlBvaWRldVU1emxBVEVSRk1tdkRBRnBT
        TDdpTDZXamhQQTNXZzFnNmFrRkYrdUxHWjRLWGlVV0VNRlNORmNFOFNtT1V4M25P
        dGZHNU9iY3h0bmNSanQ4RXhJaXVTS3BDV0VRM282SHg3U05PcVMzMW1OU3VYVlpG
        NWJ6cDFFU1lFWm1VNzJicTZSWkFlc2M1cWlUUnBMTzN2bXZ1eHdyeU02aVFXWCtl
        TlE2SVpSRks2YUV4ZFhsY04ydW8vNWtVWGVLOWZHdEQwWUE5bkRSMDQycFBxeC9S
        alpTUEl0bTBXQi9xSlp0UEhPR3BKRDdpZXZJMm8wUFpiWC8wWmpSREtvVnFDMURD
        bTRBTkt3dGI4SlFXUEJ4RnU1dVlNM21FQ3RQL1crb1lLUUdqRllXYllabWNDeUtr
        NmtuTjU1cUQ1cXN3Rk5SQW5RdDdHMmF1QVlSa3F5SWxHMEc2RHJrSFVrTG1NRm8w
        Q2tLaHhUa2MzYWkyYVVTaFNLRXpOcmlnbUl1SnlDSURGK0NrbzVFZ25oWmNEcU1a
        UUE0RkZ5eGxtYnBreTM0U3M0QlkyVmZYYlBuckw1UnRxU25JYWxqZWxhZ1pPZkJT
        WWR5dllYcTVKdXNsQlpVRndkNEtSYjU3QjVrTUZwcTYvdVF1MWdPaGM0T295S0lj
        UjBLRG1jOENxell6ZGJnODNMWHduVzZZUnVhSFhqSHZ0ZXJBL2dyTmVRTGdGWmpi
        U2F0SWZFNmZyQUMvaURtbW42eFMzQUJGZDkycnd3L1B6Qk84TXlES0lhV0R0VDR4
        SGJWbzFJaHo5TGxyV3RsMWxQcFRzQkY3a1JaQkZYZjJhcVM2NkNDdm13NUVjWDRu
        M1ZmeUU3ZDczaUd5Vlg3akwzTWo1amhGOFh6dGc0WE1RRm5EUVQ1ZmFWTndPVmtu
        Z3lSQlRKOTdYMzVKcitGYlNHUVhlUkNmbUdZTkpaWXlrZi8xcHRRbVVFY0ZqaE1D
        OVlPaFJVQjJSS0U0WHVVTXVuUmlEcW45ZDV0SjNXZTd0bGtST2dzSU5Fbm5JdkJQ
        bmlIVE11WU55VkhjSGE3SWFkSCsrSXVsM2Y5R3JHc2xlUmswU1pzWUxJOXZHYjVJ
        bGt3NHhEUThNeDJJYkFhNlA4L3JDTjVRbVpYZEVFcHk0b0VVS0J2Wm82ZWY4Sk1s
        c0Uwc2o4bjJPWEFtQnVIS1BzUGFpQWF0Zk4wSkxBNU52djdvSTJoc01YTVVjNVFS
        YjVKRjUwdnFxQlgwUUlZcldjRVhidlYyMUZpV3gwc09zVnBNMU4vTnNzZiszTkpv
        NGVsWkN2eTlCcFdydnFkNGdhTEhZbWVVeVJDcHBYeDNMeDZuTmdaajlkQUFxYjZm
        Zk16MXNpcDFkTkE3VnpLZHZlOTNGUFVUdFhYMTJJNzZDOXA1dTJxWm8rSEpHOUlD
        dWEvWWIxaUh2UHd3Sklvb1FCdy9FRFN1RitaZHh2ZkVLZUlFS24xY2V5a1lOUVhy
        Y3FkYkVMeVd5dGVLVGhtaEp0TURZV0piU3d5RXJBVDV0dXlWS1NxOW1XS3pHa0Zp
        SEg3RzVUWWVmQkJwOTdJTXpMVTVmTDRhRFNFVE9mdXBxSFp0Rlh1ckZoYjFTaGdy
        Z1llMnRaanhjUFNwTDJzcTRpa0tSQkRwL3JsU0w1dWVveUlKaXE5Wnh0V2x2MUph
        K2FrY3J3UklqSHpMbzBYK3luRmlaRDZQMzhYZ0wyY3hYL1FBQmhtTU9xeWNiUQp6
        dkVHYVJoL3hHbjRvWU5DZnByQ2IwYStzS2Y3QThndEloNXZWODRvaG5vCi0tLSBq
        Rm5NUEpwVjgwN09yWDgybC9ZeW11UmxnWTU3Q21JSzVCRDk0MTFScHdRCj0X3AMe
        1Uk8HjBgJBXmzQ4mNcN1ebqbGSjQtV8W5DND+eIQ4wEYm6TqozbdAC/qpZ1WDbHs
        ZO926ZveTMwQiV8=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-13T06:01:26Z"
  mac: ENC[AES256_GCM,data:w0E2TxA8PL8OyNxcWdrcAQHM0OoQAS6uRcJxIyVT2GGWUh1GRdR8lH1CNiTEk9IC6gvZhof3BoaEHwX8ntLpevRg5CVDCfOOxFPEdG0SuwD0inIKCVBXcvNSiJTsFag1Y6rvefpMyW+2mgt45hsUDfe/odwRm0gxQ+LpkslQZOw=,iv:hWc530GYPZJgV3e3Uk6NrGJ85Dczl0fOfVRTOpC52Nw=,tag:vsrXog62JLdGsjt/e4BvuA==,type:str]
  version: 3.13.3
