apiVersion: v1
kind: Service
metadata:
  name: headlamp
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/instance: headlamp
spec:
  selector:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/instance: headlamp
  ports:
    - name: http
      appProtocol: http
      protocol: TCP
      port: 80
      targetPort: http
