apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authelia
resources:
  - deployment.yaml
  - httproute.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
configMapGenerator:
  - name: authelia-config
    files:
      - configuration.yaml
images:
  - name: ghcr.io/authelia/authelia
    newTag: 4.39.26
    digest: sha256:16b804fbf6704b456ffb6e474c8e9d2406f9544ca0fecfeca7b4dcbed647deb4
labels:
  - pairs:
      app.kubernetes.io/part-of: authelia
      app.kubernetes.io/version: 4.39.26
