apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: headscale
resources:
  - certificate.yaml
  - deployment.yaml
  - persistentvolumeclaim.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
  - tlsroute.yaml
configMapGenerator:
  - name: headscale-config
    files:
      - config.yaml
images:
  - name: docker.io/headscale/headscale
    newTag: v0.29.4 # {"$imagepolicy": "flux-system:headscale:tag"}
    digest: sha256:8833f828b414c0907b7e5c71da76473216fe17cce0818a166b536ec552c0903f # {"$imagepolicy": "flux-system:headscale:digest"}
labels:
  - pairs:
      app.kubernetes.io/part-of: headscale
      app.kubernetes.io/version: v0.29.4 # {"$imagepolicy": "flux-system:headscale:tag"}
