---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-upgrade-controller
  namespace: flux-system
spec:
  dependsOn:
    - name: cilium
  interval: 5m0s
  path: ./infrastructure/controllers/system-upgrade-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s
  wait: true
