apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: navidrome
resources:
  - deployment.yaml
  - httproute.yaml
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
configMapGenerator:
  - name: navidrome
    files:
      - navidrome.toml
images:
  - name: docker.io/deluan/navidrome
    newTag: 0.64.1 # {"$imagepolicy": "flux-system:navidrome:tag"}
    digest: sha256:f95ebd6cb9f2eeda2da523153427c2ca994602cd2ac72d2b06067707f2d92bc4 # {"$imagepolicy": "flux-system:navidrome:digest"}
labels:
  - pairs:
      app.kubernetes.io/part-of: navidrome
      app.kubernetes.io/version: 0.64.1 # {"$imagepolicy": "flux-system:navidrome:tag"}
