apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgresql
resources:
  - database.yaml
  - databaserole.yaml
  - secret.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: authelia
      app.kubernetes.io/version: 18.6-standard-trixie
