apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: feishin
resources:
  - configmap.yaml
  - deployment.yaml
  - httproute.yaml
  - service.yaml
  - serviceaccount.yaml
images:
  - name: ghcr.io/jeffvli/feishin
    newTag: 1.17.0 # {"$imagepolicy": "flux-system:feishin:tag"}
    digest: sha256:6c75a4d3b99065ac245e2eb2b693fde3e5f2a6fe41c9e255da4fcb8948071965 # {"$imagepolicy": "flux-system:feishin:digest"}
labels:
  - pairs:
      app.kubernetes.io/part-of: feishin
      app.kubernetes.io/version: 1.17.0 # {"$imagepolicy": "flux-system:feishin:tag"}
