apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: immich
    app.kubernetes.io/component: machine-learning
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: immich
      app.kubernetes.io/instance: immich
      app.kubernetes.io/component: machine-learning
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich
        app.kubernetes.io/instance: immich
        app.kubernetes.io/component: machine-learning
    spec:
      serviceAccountName: immich-machine-learning
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: machine-learning
          image: ghcr.io/immich-app/immich-machine-learning
          envFrom:
            - configMapRef:
                name: immich-machine-learning
          ports:
            - name: http
              containerPort: 3003
              protocol: TCP
          volumeMounts:
            - name: ml-model-cache
              mountPath: /cache
            - name: ml-dotcache
              mountPath: /.cache
            - name: ml-config
              mountPath: /.config
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              cpu: 30m
              memory: 1Gi
            limits:
              cpu: 1500m
              memory: 2Gi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          startupProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: ml-model-cache
          emptyDir: {}
        - name: ml-dotcache
          emptyDir: {}
        - name: ml-config
          emptyDir: {}
        - name: tmp
          emptyDir: {}
