apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
images:
  - name: ghcr.io/immich-app/immich-machine-learning
    newTag: v3.2.1-armnn # {"$imagepolicy": "flux-system:immich-machine-learning:tag"}
    digest: sha256:9fbbe7b904de6baa1b9b4b55d2ece0f6db88dbd0f1ef83707e5a1f1ea9febab1 # {"$imagepolicy": "flux-system:immich-machine-learning:digest"}
labels:
  - pairs:
      app.kubernetes.io/part-of: immich
      app.kubernetes.io/version: v3.2.1-armnn # {"$imagepolicy": "flux-system:immich-machine-learning:tag"}
