apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
images:
  - name: ghcr.io/immich-app/immich-machine-learning
    newTag: v3.2.2-armnn # {"$imagepolicy": "flux-system:immich-machine-learning:tag"}
    digest: sha256:d43982f672e433f51f4f8172e8debe3c72edf22d4d6e2fbf171b33e96fa91b60 # {"$imagepolicy": "flux-system:immich-machine-learning:digest"}
labels:
  - pairs:
      app.kubernetes.io/part-of: immich
      app.kubernetes.io/version: v3.2.2-armnn # {"$imagepolicy": "flux-system:immich-machine-learning:tag"}
