apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: soju
resources:
  - deployment.yaml
  - httproute.yaml
  - persistentvolumeclaim.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
images:
  - name: codeberg.org/emersion/soju
    newTag: v0.11.1 # {"$imagepolicy": "flux-system:soju:tag"}
    digest: sha256:d96e0e796eab43fdea143e2ccfdd586bb5b04e3bb6a6dc544b01c35ebeaef74a # {"$imagepolicy": "flux-system:soju:digest"}
labels:
  - pairs:
      app.kubernetes.io/part-of: soju
      app.kubernetes.io/version: v0.11.1 # {"$imagepolicy": "flux-system:soju:tag"}
