apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: soju
resources:
  - deployment.yaml
  - httproute.yaml
  - persistentvolumeclaim.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
images:
  - name: codeberg.org/emersion/soju
    newTag: v0.10.1 # {"$imagepolicy": "flux-system:soju:tag"}
    digest: sha256:c0473d8f19554a03790f2a475d59646600f2f384b07b296afa782aec4c40253d # {"$imagepolicy": "flux-system:soju:digest"}
labels:
  - pairs:
      app.kubernetes.io/part-of: soju
      app.kubernetes.io/version: v0.10.1 # {"$imagepolicy": "flux-system:soju:tag"}
