---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: audiomuse-ai
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: audiomuse-ai-postgresql
    - name: keda
    - name: namespaces
  interval: 5m0s
  path: ./apps/audiomuse-ai/audiomuse-ai
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m0s
  wait: true
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: audiomuse-ai
  namespace: flux-system
spec:
  image: ghcr.io/neptunehub/audiomuse-ai
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: audiomuse-ai
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: audiomuse-ai
  filterTags:
    pattern: '^[0-9]+\.[0-9]+\.[0-9]+$'
  digestReflectionPolicy: IfNotPresent
  policy:
    semver:
      range: "3.x"
