---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: headlamp
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: namespaces
  interval: 5m0s
  path: ./apps/headlamp
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s
  wait: true
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: headlamp
  namespace: flux-system
spec:
  image: ghcr.io/headlamp-k8s/headlamp
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: headlamp
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: headlamp
  filterTags:
    pattern: '^v[0-9]+\.[0-9]+\.[0-9]+$'
  digestReflectionPolicy: IfNotPresent
  policy:
    semver:
      range: "0.x"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: headlamp-plugin-flux
  namespace: flux-system
spec:
  image: ghcr.io/headlamp-k8s/headlamp-plugin-flux
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: headlamp-plugin-flux
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: headlamp-plugin-flux
  filterTags:
    pattern: '^v[0-9]+\.[0-9]+\.[0-9]+$'
  digestReflectionPolicy: IfNotPresent
  policy:
    semver:
      range: "0.x"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: headlamp-plugin-cert-manager
  namespace: flux-system
spec:
  image: ghcr.io/headlamp-k8s/headlamp-plugin-cert-manager
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: headlamp-plugin-cert-manager
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: headlamp-plugin-cert-manager
  filterTags:
    pattern: '^v[0-9]+\.[0-9]+\.[0-9]+$'
  digestReflectionPolicy: IfNotPresent
  policy:
    semver:
      range: ">=0.1.0"
