---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich-server
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: immich-postgresql
    - name: immich-valkey
    - name: namespaces
  interval: 5m0s
  path: ./apps/immich/immich-server
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m0s
  wait: true
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: immich-server
  namespace: flux-system
spec:
  image: ghcr.io/immich-app/immich-server
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: immich-server
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: immich-server
  filterTags:
    pattern: '^v[0-9]+\.[0-9]+\.[0-9]+$'
  digestReflectionPolicy: IfNotPresent
  policy:
    semver:
      range: "3.2.x"
