---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ntfy
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: namespaces
    - name: ntfy-postgresql
  interval: 5m0s
  path: ./apps/ntfy/ntfy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s
  wait: true
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: ntfy
  namespace: flux-system
spec:
  image: docker.io/binwiederhier/ntfy
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: ntfy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ntfy
  filterTags:
    pattern: '^v[0-9]+\.[0-9]+\.[0-9]+$'
  digestReflectionPolicy: IfNotPresent
  policy:
    semver:
      range: "2.x"
