---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-metrics
  namespace: flux-system
spec:
  dependsOn:
    - name: cilium
    - name: namespaces
  interval: 5m0s
  path: ./apps/monitoring/victoria-metrics
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s
  wait: true
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: victoria-metrics
  namespace: flux-system
spec:
  image: docker.io/victoriametrics/victoria-metrics
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: victoria-metrics
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: victoria-metrics
  filterTags:
    pattern: '^v[0-9]+\.[0-9]+\.[0-9]+$'
  digestReflectionPolicy: IfNotPresent
  policy:
    semver:
      range: "1.x"
