apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
resources:
  - configmap.yaml
  - deployment.yaml
  - httproute.yaml
  - persistentvolumeclaim.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
images:
  - name: docker.io/vaultwarden/server
    newTag: 1.37.3-alpine
    digest: sha256:9a905c5cf5df61bb827da3805e160170741c0b53b0c63bb07e1afd3d2e21b1c8
labels:
  - pairs:
      app.kubernetes.io/part-of: vaultwarden
      app.kubernetes.io/version: 1.37.3-alpine
