apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
resources:
  - configmap.yaml
  - deployment.yaml
  - httproute.yaml
  - persistentvolumeclaim.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
images:
  - name: docker.io/vaultwarden/server
    newTag: 1.37.4-alpine # {"$imagepolicy": "flux-system:vaultwarden:tag"}
    digest: sha256:19ea2b669945d842dadc3d500f2d6a795866a003330f59a47b9634658bae98bb # {"$imagepolicy": "flux-system:vaultwarden:digest"}
labels:
  - pairs:
      app.kubernetes.io/part-of: vaultwarden
      app.kubernetes.io/version: 1.37.4-alpine # {"$imagepolicy": "flux-system:vaultwarden:tag"}
