apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: audiomuse-ai
resources:
  - configmap.yaml
  - httproute.yaml
  - scaledobject.yaml
  - secret.yaml
  - service-audiomuse-ai-flask-headless.yaml
  - service-audiomuse-ai-flask-service.yaml
  - service-audiomuse-ai-worker.yaml
  - serviceaccount.yaml
  - statefulset-audiomuse-ai-flask.yaml
  - statefulset-audiomuse-ai-worker.yaml
  - triggerauthentication.yaml
images:
  - name: ghcr.io/neptunehub/audiomuse-ai
    newTag: 3.6.2 # {"$imagepolicy": "flux-system:audiomuse-ai:tag"}
    digest: sha256:29e8ddb37c9c3f7fb70a8a6fab5a22e173857685edf175d2638c6c3ca8aa9eb2 # {"$imagepolicy": "flux-system:audiomuse-ai:digest"}
labels:
  - pairs:
      app.kubernetes.io/part-of: audiomuse-ai
      app.kubernetes.io/version: 3.6.2 # {"$imagepolicy": "flux-system:audiomuse-ai:tag"}
