apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: audiomuse-ai
resources:
  - configmap.yaml
  - httproute.yaml
  - scaledobject.yaml
  - secret.yaml
  - service-audiomuse-ai-flask-headless.yaml
  - service-audiomuse-ai-flask-service.yaml
  - service-audiomuse-ai-worker.yaml
  - serviceaccount.yaml
  - statefulset-audiomuse-ai-flask.yaml
  - statefulset-audiomuse-ai-worker.yaml
  - triggerauthentication.yaml
images:
  - name: ghcr.io/neptunehub/audiomuse-ai
    newTag: 3.6.3 # {"$imagepolicy": "flux-system:audiomuse-ai:tag"}
    digest: sha256:301b2d5c280f43c6e79823337455b6b7d575d7b8040a6f150266804350c51eab # {"$imagepolicy": "flux-system:audiomuse-ai:digest"}
labels:
  - pairs:
      app.kubernetes.io/part-of: audiomuse-ai
      app.kubernetes.io/version: 3.6.3 # {"$imagepolicy": "flux-system:audiomuse-ai:tag"}
