apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: ollama
data:
  HOME: /ollama
  OLLAMA_CONTEXT_LENGTH: "4096"
  OLLAMA_HOST: "[::]:11434"
  OLLAMA_KEEP_ALIVE: "-1"
  OLLAMA_MAX_LOADED_MODELS: "1"
  OLLAMA_MODEL: qwen3:1.7b
  OLLAMA_NUM_THREADS: "2"
  TZ: America/Bahia
