apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: ollama
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: ollama
      app.kubernetes.io/instance: ollama
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ollama
        app.kubernetes.io/instance: ollama
    spec:
      serviceAccountName: ollama
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: ollama
          image: docker.io/ollama/ollama
          envFrom:
            - configMapRef:
                name: ollama
          ports:
            - name: ollama
              containerPort: 11434
              protocol: TCP
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: ollama
              mountPath: /ollama
          resources:
            requests:
              cpu: 100m
              memory: 3328Mi
            limits:
              cpu: 2000m
              memory: 4Gi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - ollama run "$OLLAMA_MODEL" ""
          startupProbe:
            httpGet:
              path: /
              port: ollama
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /
              port: ollama
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: ollama
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: tmp
          emptyDir: {}
        - name: ollama
          persistentVolumeClaim:
            claimName: ollama
  strategy:
    type: Recreate
