apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ollama
resources:
  - configmap.yaml
  - deployment.yaml
  - persistentvolumeclaim.yaml
  - service.yaml
  - serviceaccount.yaml
images:
  - name: docker.io/ollama/ollama
    newTag: 0.35.0 # {"$imagepolicy": "flux-system:ollama:tag"}
    digest: sha256:2a6e883b917fc543389599dae79918f5cac9e1438890506982f44aa4f5625d01 # {"$imagepolicy": "flux-system:ollama:digest"}
labels:
  - pairs:
      app.kubernetes.io/part-of: ollama
      app.kubernetes.io/version: 0.35.0 # {"$imagepolicy": "flux-system:ollama:tag"}
