apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ollama
resources:
  - configmap.yaml
  - deployment.yaml
  - persistentvolumeclaim.yaml
  - service.yaml
  - serviceaccount.yaml
images:
  - name: docker.io/ollama/ollama
    newTag: 0.34.3 # {"$imagepolicy": "flux-system:ollama:tag"}
    digest: sha256:7ab595e4ead391f6818c7215297781282babe0701f6d9a9f8862ac591360a58b # {"$imagepolicy": "flux-system:ollama:digest"}
labels:
  - pairs:
      app.kubernetes.io/part-of: ollama
      app.kubernetes.io/version: 0.34.3 # {"$imagepolicy": "flux-system:ollama:tag"}
