apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ollama
resources:
  - configmap.yaml
  - deployment.yaml
  - persistentvolumeclaim.yaml
  - service.yaml
  - serviceaccount.yaml
images:
  - name: docker.io/ollama/ollama
    newTag: 0.40.0 # {"$imagepolicy": "flux-system:ollama:tag"}
    digest: sha256:1bef639749741b375e9a1eb2c1346fb57ce52f5432de1f74846e44ccc18e1687 # {"$imagepolicy": "flux-system:ollama:digest"}
labels:
  - pairs:
      app.kubernetes.io/part-of: ollama
      app.kubernetes.io/version: 0.40.0 # {"$imagepolicy": "flux-system:ollama:tag"}
