apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
images:
  - name: docker.io/valkey/valkey
    newTag: 9.1.2-alpine3.24 # {"$imagepolicy": "flux-system:valkey:tag"}
    digest: sha256:a174b894902bd3367e330d47cc2054367dc4917701776aaf336f41d83b65ec7a # {"$imagepolicy": "flux-system:valkey:digest"}
labels:
  - pairs:
      app.kubernetes.io/part-of: immich
      app.kubernetes.io/version: 9.1.2-alpine3.24 # {"$imagepolicy": "flux-system:valkey:tag"}
