apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
images:
  - name: docker.io/valkey/valkey
    newTag: 9.1.2-alpine3.24 # {"$imagepolicy": "flux-system:valkey:tag"}
    digest: sha256:a0dbf4c1d5708782907c10e2c72deff317518518b5288a58416981d9db95d30b # {"$imagepolicy": "flux-system:valkey:digest"}
labels:
  - pairs:
      app.kubernetes.io/part-of: immich
      app.kubernetes.io/version: 9.1.2-alpine3.24 # {"$imagepolicy": "flux-system:valkey:tag"}
