apiVersion: apps/v1
kind: Deployment
metadata:
  name: lldap
  labels:
    app.kubernetes.io/name: lldap
    app.kubernetes.io/instance: lldap
    app.kubernetes.io/component: lldap
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: lldap
      app.kubernetes.io/instance: lldap
      app.kubernetes.io/component: lldap
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lldap
        app.kubernetes.io/instance: lldap
        app.kubernetes.io/component: lldap
    spec:
      serviceAccountName: lldap
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: lldap
          image: docker.io/lldap/lldap
          envFrom:
            - configMapRef:
                name: lldap
            - secretRef:
                name: lldap
          ports:
            - name: ldap
              containerPort: 3890
              protocol: TCP
            - name: ldaps
              containerPort: 6360
              protocol: TCP
            - name: web
              containerPort: 17170
              protocol: TCP
          volumeMounts:
            - name: lldap-data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          startupProbe:
            exec:
              command:
                - /app/lldap
                - healthcheck
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 20
          livenessProbe:
            exec:
              command:
                - /app/lldap
                - healthcheck
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /app/lldap
                - healthcheck
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
      volumes:
        - name: lldap-data
          persistentVolumeClaim:
            claimName: lldap
        - name: tmp
          emptyDir: {}
