apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lldap
resources:
  - configmap.yaml
  - deployment.yaml
  - persistentvolumeclaim.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
images:
  - name: docker.io/lldap/lldap
    newTag: v0.6.3-alpine-rootless # {"$imagepolicy": "flux-system:lldap:tag"}
    digest: sha256:ba2c50930ea998eefd5454aa678a7977448019248b1827da87d330df0b71c284 # {"$imagepolicy": "flux-system:lldap:digest"}
labels:
  - pairs:
      app.kubernetes.io/part-of: lldap
      app.kubernetes.io/version: v0.6.3-alpine-rootless # {"$imagepolicy": "flux-system:lldap:tag"}
