apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - configmap.yaml
  - deployment.yaml
  - httproute.yaml
  - persistentvolumeclaim.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
configMapGenerator:
  - name: dashboards
    files:
      - dashboards/10229_rev57.json
      - dashboards/14205_rev1.json
      - dashboards/ntfy-grafana.json
  - name: provisioning-alerting
    files:
      - contact-points.yaml
  - name: provisioning-dashboards
    files:
      - dashboards.yaml
  - name: provisioning-datasources
    files:
      - datasources.yaml
images:
  - name: docker.io/grafana/grafana
    newTag: 13.2.1-slim # {"$imagepolicy": "flux-system:grafana:tag"}
    digest: sha256:2b2ca79d6fcd9b0f5d16dc8c839b46c93d2a85e72f4cef35ae4c4be0ebe65dfc # {"$imagepolicy": "flux-system:grafana:digest"}
labels:
  - pairs:
      app.kubernetes.io/part-of: monitoring
      app.kubernetes.io/version: 13.2.1-slim # {"$imagepolicy": "flux-system:grafana:tag"}
