apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - configmap.yaml
  - deployment.yaml
  - httproute.yaml
  - persistentvolumeclaim.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
configMapGenerator:
  - name: dashboards
    files:
      - dashboards/10229_rev57.json
      - dashboards/14205_rev1.json
      - dashboards/ntfy-grafana.json
  - name: provisioning-alerting
    files:
      - contact-points.yaml
  - name: provisioning-dashboards
    files:
      - dashboards.yaml
  - name: provisioning-datasources
    files:
      - datasources.yaml
images:
  - name: docker.io/grafana/grafana
    newTag: 13.2.2-slim # {"$imagepolicy": "flux-system:grafana:tag"}
    digest: sha256:979e791fc495d5ea5bf0cb39d4a36f7ceab52aa237ea76e609ea43d6a3164c88 # {"$imagepolicy": "flux-system:grafana:digest"}
labels:
  - pairs:
      app.kubernetes.io/part-of: monitoring
      app.kubernetes.io/version: 13.2.2-slim # {"$imagepolicy": "flux-system:grafana:tag"}
