apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: ntfy
  namespace: flux-system
spec:
  type: generic
  address: https://notify.guedescloud.com.br/flux-alerts
  secretRef:
    name: ntfy-headers
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHMzdE9mMVk1
        UTNkVUpJUEVPVjdyRDVkR1pGNnphR2tIZ0pWTkpBQWZRTHFtdzdCRTd4cldTYU4r
        dWo4QkNQOU85b25rdXZjc3FBN1lWOHFNZTFqVGxEUXNaakJMNnNadU9FaWdVNTc4
        Q1cvMGJjM1lydnJpN0FFQmtXTmhtK2Y0aVJvWXhweGFBTXkyWDVPb05PNUZMNk53
        eGNieW1SNGM1L0V2YWVUQVFoclZQVVVXd2JnZVZydkMzbytUV3hub2hKazE0SUp1
        cENrb3N1Wm9FdGZjWi9HSlJWQ0RYNklzdVVZdk9NRURvQVJKaWQzTjhwenI4V2ov
        Nzh5SEQrOEQ3YU5BNnFsMEZaTDlhN3VYdkRqT0xDWG9lYWo1ODdOaG1zck5pYWpi
        TWRDSWxMRkNIS2VIYS9Ea0FMekdGZ3J2L2pHcEFnZHpvUG4xcGpwMjFvZHA0ZE51
        Ti9TTldZMStLY1dHTlMxdEhmaFZzTmlBVzI1eXl4U0t5ejM3T1dOSVdaZDd2VS9z
        NjNDVGl6TThLVk9BWGF5NmNlalRnOVZMY0V6d3pjNGQva1JrcnNySkh1UU1UTjNG
        dVZUN1ViOG1PRy9pT3VQWFcyNS94Qm95Q2pLNVJISitBWTRPZEpUQkRsVncxbnli
        MnN3M05uOUowS2EwUGNWVnNpUE9rb05pUlcrSjR5aGlLenFTdmcxaU45UkVRSEhU
        RkhSVEoydzNjbWYzenY3RGYvbk84WjlaL0o1bDZCYndjYUxvcmhTUGxBUGdUY3hj
        U1ptRnZ3d3VDeUNzN0N3NzhSVVYrTVZ5SXJoVnZPdGx1ZGluUXBtdTZINS9FblNR
        bWorR3V5UGJHc0IrUHkrbExYdGQ2US9TR2k3SnFRZ3Vrelp2N0ZrbkNpTDJ4Yk9h
        K0ZOV1VnN243K29PKy9Vb1JtaEFRT2JDSG9XeloxR2p3R2pYMWdCbUZ2eTlRVE9V
        TjBXQWJWMDlmc3pGK1kvczlxZFIzeWIza1BTdXZGNVZWQU5vZURQTDFqbWE1amRY
        dTljbXlxZFFWNFlybzg3Tmk2YlNrRkNxblc1azRxdU9Uc1pOMXliRnNlTkh6aXB5
        OXprcS93bWFhZ25Lam5YZmkvb3drakp4eEJmY3U5Z1AwamRSUGl1YzlVRXBsVTd6
        RmVwdkJWcDd6L0pWS1dXK3NnZk1XM040b3licEZOYnFYbzg4WHVZL0N2bDFsUkI2
        NHczekJWZlRhcGZGUndaTXM2N1AwbW4wa3BlWXY5eXVCeGV6VTMxWERUUzVEdlpH
        RE5GaWVRSVVVNG9zb0xpTzlzb2xMK3N6elVSUHdZVWxxdG1uOGFPdUN5U2REWXRB
        akxMeUpTVytMSFl6ZkgyZlVubHFBZU5JeHpSdlhLUldmZFJUTVFoTHdzT2MwaVF4
        ajNxTDI5VGhFMWVpZU5qQktHWUVnV2xHTXJqenRXUVg2cUZGc3NuQ0NJd3MrekNk
        bkFZbUFiMUxuU09Ka2I1ajN5WHJFamdOcG9pdzVkWW40aE8vZXJLeFJtNk9DWlJN
        OCtwN0dEVFZSYW9CRENYUjFqUXZRU2RSTnVwc21XdC9RNFIxM3VLeDY0SGdVVmFP
        VHZQdjFib3RCNC9ieVdabk5KMW5NTEwwdGFWVXNiY1hlN1VPNGFKSnpxTWRBWUhX
        cEpyd2piWTNyUzUrOUFiaEY1TmR1Q2tGODJUSnc4bUQwS0RwZHdMMVFJV0tMQTRz
        a3dLZElvTEhJRGpEZFVHZWZKL0szQ2F6ZTVHcmI3MDNnY21aRWVLOVI5c2FBV2hF
        MjhDNmtsSlNHVkd5djFRcVM1anhsR1Rla0FobkZ5eDBZTVV5T2JQTkM3Zkpzb1dC
        YjhpYytXWVZId25JWXluZG1iaVB5a2dwYXkxTUhoY3NHemZkNzhNS0xPc2M2eDNW
        angyamJqSjg0cm9hZVlFcktNeUR1ekRPaEVyRmNDdmFkNm1ud2JjL3VFcUJYQQpX
        eE5UZjhMNXlhTWpyQVY4ZmdwY0N4dEFVSWg5OVJzdndtTlc4TUk4MVJNCi0tLSBO
        UkRKUENHUTRJMTRXeThndEFTMGNxVDJ1eXVVczBGNXNoWnpYcHJWeVZVCqvUUnHf
        u6FRjhGxqQl6hsrIeDwDI/JdbpM4UY5+garGYu/0kakx1+V16n6pVb2gjDwn3JY0
        TRdjwkjsEBUnCqE=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T20:26:33Z"
  mac: ENC[AES256_GCM,data:oPEv2EN9xXOhQyRVbb2CL8pLoEPuhdWXX0ixx2M/FgDTluMjGqMZE5PPtL0mT5LrH57zR5jJQ6P5zFMEI9/fgzxPAiBAfc+0geaMYs5/DpbzYtaFmNc/PQSa4Znjr5eqx0tUor4lUjBKY7biokL0BAVRMwC+uUG32vlrRb7vjM8=,iv:cIL6OYPIvgx2lnzhLZSywzhOpmSb4+SgG/jmRJusMiQ=,tag:SVLDloOU/co5Y3U3Zp0c6A==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: ntfy-headers
  namespace: flux-system
stringData:
  headers: ENC[AES256_GCM,data:ToSx1Yi9IE5PRAdtySFeHpveratp6AqUWYVLd/j44ROBiY7pnv8qW7/YC6DBNHPLnyiO+EGLGAqqAHCKm6tPU0nUgKMliA==,iv:4Ov98cKCZ5D3yWpoRlmeGNXbak46ZCaNm3/C7gOAwZg=,tag:mO473iVMFLJ1+wF+Ne0waQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHMzdE9mMVk1
        UTNkVUpJUEVPVjdyRDVkR1pGNnphR2tIZ0pWTkpBQWZRTHFtdzdCRTd4cldTYU4r
        dWo4QkNQOU85b25rdXZjc3FBN1lWOHFNZTFqVGxEUXNaakJMNnNadU9FaWdVNTc4
        Q1cvMGJjM1lydnJpN0FFQmtXTmhtK2Y0aVJvWXhweGFBTXkyWDVPb05PNUZMNk53
        eGNieW1SNGM1L0V2YWVUQVFoclZQVVVXd2JnZVZydkMzbytUV3hub2hKazE0SUp1
        cENrb3N1Wm9FdGZjWi9HSlJWQ0RYNklzdVVZdk9NRURvQVJKaWQzTjhwenI4V2ov
        Nzh5SEQrOEQ3YU5BNnFsMEZaTDlhN3VYdkRqT0xDWG9lYWo1ODdOaG1zck5pYWpi
        TWRDSWxMRkNIS2VIYS9Ea0FMekdGZ3J2L2pHcEFnZHpvUG4xcGpwMjFvZHA0ZE51
        Ti9TTldZMStLY1dHTlMxdEhmaFZzTmlBVzI1eXl4U0t5ejM3T1dOSVdaZDd2VS9z
        NjNDVGl6TThLVk9BWGF5NmNlalRnOVZMY0V6d3pjNGQva1JrcnNySkh1UU1UTjNG
        dVZUN1ViOG1PRy9pT3VQWFcyNS94Qm95Q2pLNVJISitBWTRPZEpUQkRsVncxbnli
        MnN3M05uOUowS2EwUGNWVnNpUE9rb05pUlcrSjR5aGlLenFTdmcxaU45UkVRSEhU
        RkhSVEoydzNjbWYzenY3RGYvbk84WjlaL0o1bDZCYndjYUxvcmhTUGxBUGdUY3hj
        U1ptRnZ3d3VDeUNzN0N3NzhSVVYrTVZ5SXJoVnZPdGx1ZGluUXBtdTZINS9FblNR
        bWorR3V5UGJHc0IrUHkrbExYdGQ2US9TR2k3SnFRZ3Vrelp2N0ZrbkNpTDJ4Yk9h
        K0ZOV1VnN243K29PKy9Vb1JtaEFRT2JDSG9XeloxR2p3R2pYMWdCbUZ2eTlRVE9V
        TjBXQWJWMDlmc3pGK1kvczlxZFIzeWIza1BTdXZGNVZWQU5vZURQTDFqbWE1amRY
        dTljbXlxZFFWNFlybzg3Tmk2YlNrRkNxblc1azRxdU9Uc1pOMXliRnNlTkh6aXB5
        OXprcS93bWFhZ25Lam5YZmkvb3drakp4eEJmY3U5Z1AwamRSUGl1YzlVRXBsVTd6
        RmVwdkJWcDd6L0pWS1dXK3NnZk1XM040b3licEZOYnFYbzg4WHVZL0N2bDFsUkI2
        NHczekJWZlRhcGZGUndaTXM2N1AwbW4wa3BlWXY5eXVCeGV6VTMxWERUUzVEdlpH
        RE5GaWVRSVVVNG9zb0xpTzlzb2xMK3N6elVSUHdZVWxxdG1uOGFPdUN5U2REWXRB
        akxMeUpTVytMSFl6ZkgyZlVubHFBZU5JeHpSdlhLUldmZFJUTVFoTHdzT2MwaVF4
        ajNxTDI5VGhFMWVpZU5qQktHWUVnV2xHTXJqenRXUVg2cUZGc3NuQ0NJd3MrekNk
        bkFZbUFiMUxuU09Ka2I1ajN5WHJFamdOcG9pdzVkWW40aE8vZXJLeFJtNk9DWlJN
        OCtwN0dEVFZSYW9CRENYUjFqUXZRU2RSTnVwc21XdC9RNFIxM3VLeDY0SGdVVmFP
        VHZQdjFib3RCNC9ieVdabk5KMW5NTEwwdGFWVXNiY1hlN1VPNGFKSnpxTWRBWUhX
        cEpyd2piWTNyUzUrOUFiaEY1TmR1Q2tGODJUSnc4bUQwS0RwZHdMMVFJV0tMQTRz
        a3dLZElvTEhJRGpEZFVHZWZKL0szQ2F6ZTVHcmI3MDNnY21aRWVLOVI5c2FBV2hF
        MjhDNmtsSlNHVkd5djFRcVM1anhsR1Rla0FobkZ5eDBZTVV5T2JQTkM3Zkpzb1dC
        YjhpYytXWVZId25JWXluZG1iaVB5a2dwYXkxTUhoY3NHemZkNzhNS0xPc2M2eDNW
        angyamJqSjg0cm9hZVlFcktNeUR1ekRPaEVyRmNDdmFkNm1ud2JjL3VFcUJYQQpX
        eE5UZjhMNXlhTWpyQVY4ZmdwY0N4dEFVSWg5OVJzdndtTlc4TUk4MVJNCi0tLSBO
        UkRKUENHUTRJMTRXeThndEFTMGNxVDJ1eXVVczBGNXNoWnpYcHJWeVZVCqvUUnHf
        u6FRjhGxqQl6hsrIeDwDI/JdbpM4UY5+garGYu/0kakx1+V16n6pVb2gjDwn3JY0
        TRdjwkjsEBUnCqE=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T20:26:33Z"
  mac: ENC[AES256_GCM,data:oPEv2EN9xXOhQyRVbb2CL8pLoEPuhdWXX0ixx2M/FgDTluMjGqMZE5PPtL0mT5LrH57zR5jJQ6P5zFMEI9/fgzxPAiBAfc+0geaMYs5/DpbzYtaFmNc/PQSa4Znjr5eqx0tUor4lUjBKY7biokL0BAVRMwC+uUG32vlrRb7vjM8=,iv:cIL6OYPIvgx2lnzhLZSywzhOpmSb4+SgG/jmRJusMiQ=,tag:SVLDloOU/co5Y3U3Zp0c6A==,type:str]
  version: 3.13.3
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: ntfy
  namespace: flux-system
spec:
  providerRef:
    name: ntfy
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      name: '*'
    - kind: ImagePolicy
      name: '*'
    - kind: ImageUpdateAutomation
      name: flux-system
    - kind: OCIRepository
      name: '*'
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHMzdE9mMVk1
        UTNkVUpJUEVPVjdyRDVkR1pGNnphR2tIZ0pWTkpBQWZRTHFtdzdCRTd4cldTYU4r
        dWo4QkNQOU85b25rdXZjc3FBN1lWOHFNZTFqVGxEUXNaakJMNnNadU9FaWdVNTc4
        Q1cvMGJjM1lydnJpN0FFQmtXTmhtK2Y0aVJvWXhweGFBTXkyWDVPb05PNUZMNk53
        eGNieW1SNGM1L0V2YWVUQVFoclZQVVVXd2JnZVZydkMzbytUV3hub2hKazE0SUp1
        cENrb3N1Wm9FdGZjWi9HSlJWQ0RYNklzdVVZdk9NRURvQVJKaWQzTjhwenI4V2ov
        Nzh5SEQrOEQ3YU5BNnFsMEZaTDlhN3VYdkRqT0xDWG9lYWo1ODdOaG1zck5pYWpi
        TWRDSWxMRkNIS2VIYS9Ea0FMekdGZ3J2L2pHcEFnZHpvUG4xcGpwMjFvZHA0ZE51
        Ti9TTldZMStLY1dHTlMxdEhmaFZzTmlBVzI1eXl4U0t5ejM3T1dOSVdaZDd2VS9z
        NjNDVGl6TThLVk9BWGF5NmNlalRnOVZMY0V6d3pjNGQva1JrcnNySkh1UU1UTjNG
        dVZUN1ViOG1PRy9pT3VQWFcyNS94Qm95Q2pLNVJISitBWTRPZEpUQkRsVncxbnli
        MnN3M05uOUowS2EwUGNWVnNpUE9rb05pUlcrSjR5aGlLenFTdmcxaU45UkVRSEhU
        RkhSVEoydzNjbWYzenY3RGYvbk84WjlaL0o1bDZCYndjYUxvcmhTUGxBUGdUY3hj
        U1ptRnZ3d3VDeUNzN0N3NzhSVVYrTVZ5SXJoVnZPdGx1ZGluUXBtdTZINS9FblNR
        bWorR3V5UGJHc0IrUHkrbExYdGQ2US9TR2k3SnFRZ3Vrelp2N0ZrbkNpTDJ4Yk9h
        K0ZOV1VnN243K29PKy9Vb1JtaEFRT2JDSG9XeloxR2p3R2pYMWdCbUZ2eTlRVE9V
        TjBXQWJWMDlmc3pGK1kvczlxZFIzeWIza1BTdXZGNVZWQU5vZURQTDFqbWE1amRY
        dTljbXlxZFFWNFlybzg3Tmk2YlNrRkNxblc1azRxdU9Uc1pOMXliRnNlTkh6aXB5
        OXprcS93bWFhZ25Lam5YZmkvb3drakp4eEJmY3U5Z1AwamRSUGl1YzlVRXBsVTd6
        RmVwdkJWcDd6L0pWS1dXK3NnZk1XM040b3licEZOYnFYbzg4WHVZL0N2bDFsUkI2
        NHczekJWZlRhcGZGUndaTXM2N1AwbW4wa3BlWXY5eXVCeGV6VTMxWERUUzVEdlpH
        RE5GaWVRSVVVNG9zb0xpTzlzb2xMK3N6elVSUHdZVWxxdG1uOGFPdUN5U2REWXRB
        akxMeUpTVytMSFl6ZkgyZlVubHFBZU5JeHpSdlhLUldmZFJUTVFoTHdzT2MwaVF4
        ajNxTDI5VGhFMWVpZU5qQktHWUVnV2xHTXJqenRXUVg2cUZGc3NuQ0NJd3MrekNk
        bkFZbUFiMUxuU09Ka2I1ajN5WHJFamdOcG9pdzVkWW40aE8vZXJLeFJtNk9DWlJN
        OCtwN0dEVFZSYW9CRENYUjFqUXZRU2RSTnVwc21XdC9RNFIxM3VLeDY0SGdVVmFP
        VHZQdjFib3RCNC9ieVdabk5KMW5NTEwwdGFWVXNiY1hlN1VPNGFKSnpxTWRBWUhX
        cEpyd2piWTNyUzUrOUFiaEY1TmR1Q2tGODJUSnc4bUQwS0RwZHdMMVFJV0tMQTRz
        a3dLZElvTEhJRGpEZFVHZWZKL0szQ2F6ZTVHcmI3MDNnY21aRWVLOVI5c2FBV2hF
        MjhDNmtsSlNHVkd5djFRcVM1anhsR1Rla0FobkZ5eDBZTVV5T2JQTkM3Zkpzb1dC
        YjhpYytXWVZId25JWXluZG1iaVB5a2dwYXkxTUhoY3NHemZkNzhNS0xPc2M2eDNW
        angyamJqSjg0cm9hZVlFcktNeUR1ekRPaEVyRmNDdmFkNm1ud2JjL3VFcUJYQQpX
        eE5UZjhMNXlhTWpyQVY4ZmdwY0N4dEFVSWg5OVJzdndtTlc4TUk4MVJNCi0tLSBO
        UkRKUENHUTRJMTRXeThndEFTMGNxVDJ1eXVVczBGNXNoWnpYcHJWeVZVCqvUUnHf
        u6FRjhGxqQl6hsrIeDwDI/JdbpM4UY5+garGYu/0kakx1+V16n6pVb2gjDwn3JY0
        TRdjwkjsEBUnCqE=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T20:26:33Z"
  mac: ENC[AES256_GCM,data:oPEv2EN9xXOhQyRVbb2CL8pLoEPuhdWXX0ixx2M/FgDTluMjGqMZE5PPtL0mT5LrH57zR5jJQ6P5zFMEI9/fgzxPAiBAfc+0geaMYs5/DpbzYtaFmNc/PQSa4Znjr5eqx0tUor4lUjBKY7biokL0BAVRMwC+uUG32vlrRb7vjM8=,iv:cIL6OYPIvgx2lnzhLZSywzhOpmSb4+SgG/jmRJusMiQ=,tag:SVLDloOU/co5Y3U3Zp0c6A==,type:str]
  version: 3.13.3
