apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: ntfy
  namespace: flux-system
spec:
  type: generic
  address: https://notify.guedescloud.com.br/flux-alerts
  secretRef:
    name: ntfy-headers
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGl1Ykw1Nith
        WFlkWXBKS1JDR3g4ZEdGdTBZelovamR3T0Y2S29mQnBtTFQrQXhwWWwwWXdPQkFF
        N0JxZHZMeEkxcDlnc2RucDdGcndwMm11TGpFOHNlV1JnQXhkbXZBTUNzMUxpVkhU
        VzBDVWNYc3ZMbjVoZVIxYWtiUk1PSVZrdWV0d01TTTF0VnVtRGxWMjBzTnFCUSs5
        UHdVUkI5R0VkbjZoUDErWmFhOUVUYXNROE5nZ1l1aFQ3aXR4V25OcDZCbnBiNDNO
        a1R6VStVeHNvbHhNVzh5QldjWS94eGdCUTFUVkp5TmsyVVdkYTJ5WjBXd1d0Y1NM
        Q0J5THlSWHpaNnJkR250U0t5RkdSWUQwMDlFZFc3ZzQzV2p4TzBmTU50cHI5ZlZh
        U2FHVGlQazBPY2F5UFBPbGhzZkp2TjR0OEN0aGZRRElpYlZ2dWxCcDhxNlhFdm1i
        aHQ5L2VoNFJhRDA1LzRFcUpKa0VJVFV0bXFBVy9iRzVSZTdUKzRsU0JmUU5SUHpx
        eWRta2tDZ2V5Y3cxTjdsTFEwYTJDY1I1VE5DK0FKUzlWNiswQmFJbDE3czZtd0pw
        THVmeFZNSzdFWHpjdTJZdnRzanZ5MHV2bmVlTXdaWjBzcXB0Q3AvdFhkRlQxWUpH
        aDJaTHEwUWlGcVdBUnE5Zk1pSWhZMlhSTncyRUxxZXFDdVN0RDFsVGtvZk9KUHll
        SkVYMldnR09NWktjZ3pHMi9NazVWdm1rc3V3c0tKZG9wVFA1Z2VxN0pCY3JYMi9n
        Z3FaS3RDaXdRNXA5M1ZINDFmZWhZSCtISXkveUk3VENoUnBuTU01Y2IyaGZrUzE4
        SUJvRlUzaVVuajNKWWlEazBvMWdYSDdWdWNKQkpnamFHNlNDNnYrMFpDaTI3RnFR
        cURjcmhFcXZ5SXFzQWdROUhGVGgzaUE0ai9JdjR6RXNzeHBJZkp5R3JlSkZHV0pv
        UHFGVUlPK00xTXNPTVlMODZqd0RpcWtuMVBHeldadzBrbCtOQlBrRGxoUms3ZTN5
        N1hHYytjYk9LRlUvTDRuazdObWZ1OHBnNXdrUnNyekVGaklPZ0ppcUNnNGhjaUh4
        aWNCdmpPUGl0QmNtb2psYVVCSzFCYythYnhSUkY4Tk9tZFJDbUh6cHpkRm10RVBy
        RWVWYkJsTjBmWEgxK01xT2tmWjdvVWNPZGdTdUJRb2d6MzZibGg2UVJJUVExNWFS
        c3NrK0dSVEFpcHpFaU1EcndCK2V2VUtFSW0rczVWOTNLaDI5RVovcy9uL05jQlJH
        ZWdwZ2pyOUhDbnU0ekJVejlVRi9tWU5QY1lsc3pBT0FuLzYxMUFZRmJzNm9YU2lF
        SmNwNGp6c0hFSWNFRVpGRVVqeWVpWnE1RldlWUFQKzNtaHhoem1tcWE2UUswdENj
        QXBNcXVEMkNvL3lncjMyMGVEcEZ4a084bkxqOGcrZGFEMzZIdCt5Y3V6dFBtNzAr
        RUVwdE14YmhvVndSTjYwcUR1NXhXdzFLV2dOVjZsSG1NdFRJWjZHTTFZSXVONjY3
        RWZ1bnhhMXJ6WDRJQThKSE9ySE5aNlBha3hxclZFaDNGT3NRR2xFaW0zSDdDUFdt
        RUJhS3M4eUYwdDFFNHY1dzhxM2hGazFXVHlPalNQbjI0SE5ZZ1RuOEFMbTdnUlNV
        aWVpRkJMcXE3TFpEOVMxRTUyaXUrQlNGUk5DTnpMYVpwSlNPa3l2U3YrazVuSkdV
        bWU3dWRkeWRxOS95ODNpSVJ3WWNoVEJJMnd1S2QwdU1hOXMyd2lwdjhLMUErZjR4
        TkFaTE42UEFqbGxHTCtPVE51akJLM2JmTjIyeHp2OXBRcFErK21ONzNTbFdoNHo4
        UHkvYTREeDZHbWtONktHS0pYUk1MVWhKMjRnekllOXRZaFdIOTdkRWJrY0tYOGx3
        YUlVdmhmYUJoLzZjQk1DZkVIcW1Ha2Z5MUVQcnNOdG1SRVROUUE2KzhKZ1hZUQpj
        TWtJWDY1NUZ2UkNscUFMbWZ1UGlNOVI0NUpzMzU2d2YzR1A5YnQ2ODhnCi0tLSBJ
        Z3ptQ0NzOW91bHhVWGd3aXZJT0p1Ym1Bc2VhcFNWRko2SUtjTWZIOFRJCnGupp63
        CvO8qUssjOfrX1lhWIhyg0r3paoWzBFBwJ1fFHgF2HerDK0i7lpS5BENo/t/IRep
        h4BMMCfeDZZKSHA=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T22:05:58Z"
  mac: ENC[AES256_GCM,data:0B2Qh5ho9syQVZfMOkKGJPD6Cnq7BrU/hy7My+BJuBIwj+b7r5ID97L5A728eJ5sPWa9rWrf6hjOiIfhlLI09md5io4jHMoX2Fn6qUM6rmI+cBGMOxOEa9jjTzWjQtLOSIqomdaxt1J6s57BkEb/JUNWl5NmAc0kJ+bj1OAJIzc=,iv:vpxptmw+Pyo8Vx/gd1CoEYXINbb6+ukdSxurnnzb+L8=,tag:fTVF+iggz8t7KSt+5NPGzg==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: ntfy-headers
  namespace: flux-system
stringData:
  headers: ENC[AES256_GCM,data:yyOz34LU6/ZrMknRX/uyCYKZIQHyTNCV91vAztvJlQus6hqFZ3Wzu55vRwoJlevepaVlUVM40ntwvoq04IY+tZd91/nWCQ==,iv:YnDz5b+HJMy0WZEoJBC+pJMKssNVMk+duwo86HoV4/8=,tag:ktCXBN0G2qZ/ZWuCGw+Jqw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGl1Ykw1Nith
        WFlkWXBKS1JDR3g4ZEdGdTBZelovamR3T0Y2S29mQnBtTFQrQXhwWWwwWXdPQkFF
        N0JxZHZMeEkxcDlnc2RucDdGcndwMm11TGpFOHNlV1JnQXhkbXZBTUNzMUxpVkhU
        VzBDVWNYc3ZMbjVoZVIxYWtiUk1PSVZrdWV0d01TTTF0VnVtRGxWMjBzTnFCUSs5
        UHdVUkI5R0VkbjZoUDErWmFhOUVUYXNROE5nZ1l1aFQ3aXR4V25OcDZCbnBiNDNO
        a1R6VStVeHNvbHhNVzh5QldjWS94eGdCUTFUVkp5TmsyVVdkYTJ5WjBXd1d0Y1NM
        Q0J5THlSWHpaNnJkR250U0t5RkdSWUQwMDlFZFc3ZzQzV2p4TzBmTU50cHI5ZlZh
        U2FHVGlQazBPY2F5UFBPbGhzZkp2TjR0OEN0aGZRRElpYlZ2dWxCcDhxNlhFdm1i
        aHQ5L2VoNFJhRDA1LzRFcUpKa0VJVFV0bXFBVy9iRzVSZTdUKzRsU0JmUU5SUHpx
        eWRta2tDZ2V5Y3cxTjdsTFEwYTJDY1I1VE5DK0FKUzlWNiswQmFJbDE3czZtd0pw
        THVmeFZNSzdFWHpjdTJZdnRzanZ5MHV2bmVlTXdaWjBzcXB0Q3AvdFhkRlQxWUpH
        aDJaTHEwUWlGcVdBUnE5Zk1pSWhZMlhSTncyRUxxZXFDdVN0RDFsVGtvZk9KUHll
        SkVYMldnR09NWktjZ3pHMi9NazVWdm1rc3V3c0tKZG9wVFA1Z2VxN0pCY3JYMi9n
        Z3FaS3RDaXdRNXA5M1ZINDFmZWhZSCtISXkveUk3VENoUnBuTU01Y2IyaGZrUzE4
        SUJvRlUzaVVuajNKWWlEazBvMWdYSDdWdWNKQkpnamFHNlNDNnYrMFpDaTI3RnFR
        cURjcmhFcXZ5SXFzQWdROUhGVGgzaUE0ai9JdjR6RXNzeHBJZkp5R3JlSkZHV0pv
        UHFGVUlPK00xTXNPTVlMODZqd0RpcWtuMVBHeldadzBrbCtOQlBrRGxoUms3ZTN5
        N1hHYytjYk9LRlUvTDRuazdObWZ1OHBnNXdrUnNyekVGaklPZ0ppcUNnNGhjaUh4
        aWNCdmpPUGl0QmNtb2psYVVCSzFCYythYnhSUkY4Tk9tZFJDbUh6cHpkRm10RVBy
        RWVWYkJsTjBmWEgxK01xT2tmWjdvVWNPZGdTdUJRb2d6MzZibGg2UVJJUVExNWFS
        c3NrK0dSVEFpcHpFaU1EcndCK2V2VUtFSW0rczVWOTNLaDI5RVovcy9uL05jQlJH
        ZWdwZ2pyOUhDbnU0ekJVejlVRi9tWU5QY1lsc3pBT0FuLzYxMUFZRmJzNm9YU2lF
        SmNwNGp6c0hFSWNFRVpGRVVqeWVpWnE1RldlWUFQKzNtaHhoem1tcWE2UUswdENj
        QXBNcXVEMkNvL3lncjMyMGVEcEZ4a084bkxqOGcrZGFEMzZIdCt5Y3V6dFBtNzAr
        RUVwdE14YmhvVndSTjYwcUR1NXhXdzFLV2dOVjZsSG1NdFRJWjZHTTFZSXVONjY3
        RWZ1bnhhMXJ6WDRJQThKSE9ySE5aNlBha3hxclZFaDNGT3NRR2xFaW0zSDdDUFdt
        RUJhS3M4eUYwdDFFNHY1dzhxM2hGazFXVHlPalNQbjI0SE5ZZ1RuOEFMbTdnUlNV
        aWVpRkJMcXE3TFpEOVMxRTUyaXUrQlNGUk5DTnpMYVpwSlNPa3l2U3YrazVuSkdV
        bWU3dWRkeWRxOS95ODNpSVJ3WWNoVEJJMnd1S2QwdU1hOXMyd2lwdjhLMUErZjR4
        TkFaTE42UEFqbGxHTCtPVE51akJLM2JmTjIyeHp2OXBRcFErK21ONzNTbFdoNHo4
        UHkvYTREeDZHbWtONktHS0pYUk1MVWhKMjRnekllOXRZaFdIOTdkRWJrY0tYOGx3
        YUlVdmhmYUJoLzZjQk1DZkVIcW1Ha2Z5MUVQcnNOdG1SRVROUUE2KzhKZ1hZUQpj
        TWtJWDY1NUZ2UkNscUFMbWZ1UGlNOVI0NUpzMzU2d2YzR1A5YnQ2ODhnCi0tLSBJ
        Z3ptQ0NzOW91bHhVWGd3aXZJT0p1Ym1Bc2VhcFNWRko2SUtjTWZIOFRJCnGupp63
        CvO8qUssjOfrX1lhWIhyg0r3paoWzBFBwJ1fFHgF2HerDK0i7lpS5BENo/t/IRep
        h4BMMCfeDZZKSHA=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T22:05:58Z"
  mac: ENC[AES256_GCM,data:0B2Qh5ho9syQVZfMOkKGJPD6Cnq7BrU/hy7My+BJuBIwj+b7r5ID97L5A728eJ5sPWa9rWrf6hjOiIfhlLI09md5io4jHMoX2Fn6qUM6rmI+cBGMOxOEa9jjTzWjQtLOSIqomdaxt1J6s57BkEb/JUNWl5NmAc0kJ+bj1OAJIzc=,iv:vpxptmw+Pyo8Vx/gd1CoEYXINbb6+ukdSxurnnzb+L8=,tag:fTVF+iggz8t7KSt+5NPGzg==,type:str]
  version: 3.13.3
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: ntfy
  namespace: flux-system
spec:
  providerRef:
    name: ntfy
  eventSeverity: info
  eventSources:
    - kind: ImageUpdateAutomation
      name: flux-system
    - kind: ImagePolicy
      name: '*'
    - kind: HelmRelease
      name: '*'
      namespace: cert-manager
    - kind: OCIRepository
      name: '*'
      namespace: cert-manager
    - kind: HelmRelease
      name: '*'
      namespace: kube-system
    - kind: OCIRepository
      name: '*'
      namespace: kube-system
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGl1Ykw1Nith
        WFlkWXBKS1JDR3g4ZEdGdTBZelovamR3T0Y2S29mQnBtTFQrQXhwWWwwWXdPQkFF
        N0JxZHZMeEkxcDlnc2RucDdGcndwMm11TGpFOHNlV1JnQXhkbXZBTUNzMUxpVkhU
        VzBDVWNYc3ZMbjVoZVIxYWtiUk1PSVZrdWV0d01TTTF0VnVtRGxWMjBzTnFCUSs5
        UHdVUkI5R0VkbjZoUDErWmFhOUVUYXNROE5nZ1l1aFQ3aXR4V25OcDZCbnBiNDNO
        a1R6VStVeHNvbHhNVzh5QldjWS94eGdCUTFUVkp5TmsyVVdkYTJ5WjBXd1d0Y1NM
        Q0J5THlSWHpaNnJkR250U0t5RkdSWUQwMDlFZFc3ZzQzV2p4TzBmTU50cHI5ZlZh
        U2FHVGlQazBPY2F5UFBPbGhzZkp2TjR0OEN0aGZRRElpYlZ2dWxCcDhxNlhFdm1i
        aHQ5L2VoNFJhRDA1LzRFcUpKa0VJVFV0bXFBVy9iRzVSZTdUKzRsU0JmUU5SUHpx
        eWRta2tDZ2V5Y3cxTjdsTFEwYTJDY1I1VE5DK0FKUzlWNiswQmFJbDE3czZtd0pw
        THVmeFZNSzdFWHpjdTJZdnRzanZ5MHV2bmVlTXdaWjBzcXB0Q3AvdFhkRlQxWUpH
        aDJaTHEwUWlGcVdBUnE5Zk1pSWhZMlhSTncyRUxxZXFDdVN0RDFsVGtvZk9KUHll
        SkVYMldnR09NWktjZ3pHMi9NazVWdm1rc3V3c0tKZG9wVFA1Z2VxN0pCY3JYMi9n
        Z3FaS3RDaXdRNXA5M1ZINDFmZWhZSCtISXkveUk3VENoUnBuTU01Y2IyaGZrUzE4
        SUJvRlUzaVVuajNKWWlEazBvMWdYSDdWdWNKQkpnamFHNlNDNnYrMFpDaTI3RnFR
        cURjcmhFcXZ5SXFzQWdROUhGVGgzaUE0ai9JdjR6RXNzeHBJZkp5R3JlSkZHV0pv
        UHFGVUlPK00xTXNPTVlMODZqd0RpcWtuMVBHeldadzBrbCtOQlBrRGxoUms3ZTN5
        N1hHYytjYk9LRlUvTDRuazdObWZ1OHBnNXdrUnNyekVGaklPZ0ppcUNnNGhjaUh4
        aWNCdmpPUGl0QmNtb2psYVVCSzFCYythYnhSUkY4Tk9tZFJDbUh6cHpkRm10RVBy
        RWVWYkJsTjBmWEgxK01xT2tmWjdvVWNPZGdTdUJRb2d6MzZibGg2UVJJUVExNWFS
        c3NrK0dSVEFpcHpFaU1EcndCK2V2VUtFSW0rczVWOTNLaDI5RVovcy9uL05jQlJH
        ZWdwZ2pyOUhDbnU0ekJVejlVRi9tWU5QY1lsc3pBT0FuLzYxMUFZRmJzNm9YU2lF
        SmNwNGp6c0hFSWNFRVpGRVVqeWVpWnE1RldlWUFQKzNtaHhoem1tcWE2UUswdENj
        QXBNcXVEMkNvL3lncjMyMGVEcEZ4a084bkxqOGcrZGFEMzZIdCt5Y3V6dFBtNzAr
        RUVwdE14YmhvVndSTjYwcUR1NXhXdzFLV2dOVjZsSG1NdFRJWjZHTTFZSXVONjY3
        RWZ1bnhhMXJ6WDRJQThKSE9ySE5aNlBha3hxclZFaDNGT3NRR2xFaW0zSDdDUFdt
        RUJhS3M4eUYwdDFFNHY1dzhxM2hGazFXVHlPalNQbjI0SE5ZZ1RuOEFMbTdnUlNV
        aWVpRkJMcXE3TFpEOVMxRTUyaXUrQlNGUk5DTnpMYVpwSlNPa3l2U3YrazVuSkdV
        bWU3dWRkeWRxOS95ODNpSVJ3WWNoVEJJMnd1S2QwdU1hOXMyd2lwdjhLMUErZjR4
        TkFaTE42UEFqbGxHTCtPVE51akJLM2JmTjIyeHp2OXBRcFErK21ONzNTbFdoNHo4
        UHkvYTREeDZHbWtONktHS0pYUk1MVWhKMjRnekllOXRZaFdIOTdkRWJrY0tYOGx3
        YUlVdmhmYUJoLzZjQk1DZkVIcW1Ha2Z5MUVQcnNOdG1SRVROUUE2KzhKZ1hZUQpj
        TWtJWDY1NUZ2UkNscUFMbWZ1UGlNOVI0NUpzMzU2d2YzR1A5YnQ2ODhnCi0tLSBJ
        Z3ptQ0NzOW91bHhVWGd3aXZJT0p1Ym1Bc2VhcFNWRko2SUtjTWZIOFRJCnGupp63
        CvO8qUssjOfrX1lhWIhyg0r3paoWzBFBwJ1fFHgF2HerDK0i7lpS5BENo/t/IRep
        h4BMMCfeDZZKSHA=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1pcc952wp5r5svd72s6anpqzpth2m3lzzp7t5p072dxss4jeymjwrrq8gw5c7szx0lwtazuyvnlupq5n8zv2nxhq7yzwp34pkxdvnaj2u3evlddrkyqxrje255vefhhru9jzqe9z7yja78wgw5ffvlzlqcgrrsu5n0dpaxf9ra8gzdryyht90z4w45wa03keqrgfxyfmrsz30wz7dkgrhr6us499q2pnuj6pthq48qksqmqy8tlpnfv7qr2kswqycnsdal5srludhclg80enjvth6ngmfwmp82u3thdsjghge5zs77qqzm5as39v4e6mxz8lf8g0wg3ds6gaguhj9f3hqs448c988x4hcqyfe97urr00qhverqec22flfkgkgngs8awpkwjeez93mp0zuk7agmygmdrcy8z9zsp6z27sl8f3x6tsgelg3gf8tj86pedvp0etllw3qqyw6wpdq0fggq7qcv6xw6eghzdhv0ljkwwg5v9ahdsy5ngs6673khfhqr8ae7yggk29mhqncgttx966fhfvq329edcza827tgmwvnj60x6hg4qnz4stsnfncmk6m0t00czqrpzuskvm368yth2s9gev0k7g762h6gx6709sred9qp6gr0qes9jadv3d94pynkpjhwmz449ypfy3pdqvhhn78zj92p9snqqqxavz8lzk88mcjdkeqhqvz4dgffja78pe44cukue7vxwdfstwgj24p4632fmzmnfrevst44ssr42kz064ez49mtyjvxmegrdsvadv8k635qffefl42w90f56mn5g0ww725tlay8hsuvevth0uh8vjjfaagkygr3cp3xpjuc9rwc2nyup6df4pk669f256m3ny3s53s6z6ra3sr773803z6z6f70zdqd2uxd36xtanrszj8scq882u8djntyreylvn9gppfyr4xgf67e7at542222cvyusm8jchcqzy7xpuh6v88qf59cw7j5vmmx53q2cpvdgsxeeptyp9tq4pvxshkz9c9muv6lz5ttupxss43z4er7tnsdg42kfzy2qvtfsypfk7wqupv63kg9kfp30nyqcf02v8pd5gl0dzj02eheq35u8fxy705wmu9gp9ytptetz9yrdszzxmszac90un82sgvf42g4v4jp9f4a70gkazhf5vng2pct7z99ggh46lccwgvfjxvmwfz5ff8j5jmzrhpu9nzmtvr8x8evn82gl9h6p5gkm28uhurlwtg32uh8yst3zlq9xygwu2hcm32lj0f3h0kecvvd4m59gteyjs9zpelyj90k4p0g9jrsz5y8edjrhdzanrm353xd6hymuh2qu890k97dgp3ppds56gsza50ddcxve36xr3f4ft08dxlax5589nscuagaa8v0zcntf4d5asrzu8jknr42rk2y34mu54r0cjc0quy278yf657ez2nt33cr9qy3xesvx9uc60juwteuqvttec8knag9mv3q0d3jq9dau8cp5295m4dzjzya384k36rpjgl85r5weaqk60vlymnuugzpj5tyur3sxjds7p55ndjeflhu237zuu84fdpze2csnqzf3ak8q6qz7cjxsaqjhnv5y5ysp99w35u6rxs4u0f03ks7tv9de90cv5cca6sq2pfr6mv4nw8eu52qtp93dn4hgnzfven2r3lrpwelkr3mrpwn4wcrwcqjzytcuzse54ug9hdfnxn8f6edpqy9ztjwnp9mfy2w32keapqjk8dcvjd6n6yzkk2hry55d8cww4p74sdgwrghh84hx4wg57udyul3tmzpmfue7te9wtrxpn6gu287eu42xz2h3f88genu26030ve4nwvs0xcghmflvcjpp0sk5h9476vezhvp2k3kqyjvvt57qel7y8n4f70kn5ffna4m20x3pn2uy3d5c2ywqt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T22:05:58Z"
  mac: ENC[AES256_GCM,data:0B2Qh5ho9syQVZfMOkKGJPD6Cnq7BrU/hy7My+BJuBIwj+b7r5ID97L5A728eJ5sPWa9rWrf6hjOiIfhlLI09md5io4jHMoX2Fn6qUM6rmI+cBGMOxOEa9jjTzWjQtLOSIqomdaxt1J6s57BkEb/JUNWl5NmAc0kJ+bj1OAJIzc=,iv:vpxptmw+Pyo8Vx/gd1CoEYXINbb6+ukdSxurnnzb+L8=,tag:fTVF+iggz8t7KSt+5NPGzg==,type:str]
  version: 3.13.3
