---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        {{- $apps := list -}}
        {{- $version := "" -}}
        {{- range .Changed.Changes -}}
          {{- if hasSuffix ":tag" .Setter -}}
            {{- $appName := regexReplaceAll ".*:([^:]+):tag" .Setter "$1" -}}
            {{- if not (has $appName $apps) -}}
              {{- $apps = append $apps $appName -}}
              {{- $version = .NewValue -}}
            {{- end -}}
          {{- end -}}
        {{- end -}}
        {{- if eq (len $apps) 1 -}}
        chore({{ first $apps }}): update version to {{ $version }}
        {{- else -}}
        chore: update container images
        {{- end -}}
    push:
      branch: master
  update:
    path: .
    strategy: Setters
