apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - service-prometheus.yaml
  - service-victoria-metrics.yaml
  - serviceaccount.yaml
  - statefulset.yaml
images:
  - name: docker.io/victoriametrics/victoria-metrics
    newTag: v1.152.0 # {"$imagepolicy": "flux-system:victoria-metrics:tag"}
    digest: sha256:86ca5fdb6d87d56ba047b044039019ba2bd9042b36e35f6ea34e437b6c825cef # {"$imagepolicy": "flux-system:victoria-metrics:digest"}
labels:
  - pairs:
      app.kubernetes.io/part-of: monitoring
      app.kubernetes.io/version: v1.152.0 # {"$imagepolicy": "flux-system:victoria-metrics:tag"}
